version: '3.9'

services:
  postgres:
    image: postgres:14.2-alpine3.15
    container_name: postgredb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: tcabalak
    volumes:
      - postgres:/data/postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    links:
      - postgres

volumes:
  postgres:
  pgadmin: